import "@/styles/globals.css";

import { Toaster } from "@/components/ui/toaster";
import SideBar from "@/components/navbar/SideBar";
import { Providers } from "./providers";
import AlertMessages from "@/components/AlertMessages";
import OfflineBanner from "@/components/OfflineBanner";

export const metadata = {
  title: "Point Of Sales | 4D Comfort",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="POS" />
      </head>
      <body className="ml-0 sm:ml-20">
        <Providers>
          <SideBar />
          <AlertMessages />
          {children}
          <Toaster />
          <OfflineBanner />
        </Providers>
      </body>
    </html>
  );
}
