import "@/styles/globals.css";

import { Toaster } from "@/components/ui/toaster";
import SideBar from "@/components/navbar/SideBar";
import { Providers } from "./providers";
import AlertMessages from "@/components/AlertMessages";

export const metadata = {
  title: "Point Of Sales | 4D Comfort",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </head>
      <body className="ml-0 sm:ml-20">
        <Providers>
          <SideBar />
          <AlertMessages />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
